name : compile and deploy

on:
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
      - main
    paths:
      - ".github/workflows/**"
      - "GithubActionsDemoApp/**"
      - "Tests/**"
env:
  DOTNET_VERSION: 8.0.x
  Project_name: GithubActionsDemoApp/GithubActionsDemoApp.csproj

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the code
        uses: actions/checkout@v6.0.2
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      # Just separate this 2 steps so if it fails we know where
      - name: Getting the dependencies
        run: dotnet restore

      - name: Compile
        run: dotnet build --no-restore

      - name: test the application in sequential
        run: dotnet test --no-build

      - name: Publish application
        run: dotnet publish ${{env.Project_name}} -c Release -o myapp --runtime win-x86

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          path: ./myapp
          name: build

      
          
      
   
